### ISSUE TITLE
Ajout des articles de Poivron sur la localisation des robots holonomes

### ISSUE THREAD

**Issue by nadarbreicq** [VRAC-team/la-maxi-liste-ressources-eurobot#7]
Yo ! L'équipe Poivron a fait 3 articles super interessants sur la localisation des robots holonomes : 

- http://poivron-robotique.fr/Robot-holonome-localisation-partie-1.html
- http://poivron-robotique.fr/Robot-holonome-localisation-partie-2.html
- http://poivron-robotique.fr/Robot-holonome-lois-de-commande.html

A rajouter dans la partie "Base roulante" à mon avis ;)

**Comment by monowii** [comment]
done!
